version: '3'
services:
  mongodb:
    image: mongo:latest
    command: mongod
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: remotr
    ports:
      - 27017:27017
    volumes:
      - ./data/docker-entrypoint-initdb.d/00-mongo-init.js:/docker-entrypoint-initdb.d/00-mongo-init.js
