// Script to set up the application database
// DO NOT EDIT THIS FILE DIRECTLY - configuration values are interpolated from .env by scripts/generate-db-init-script.js
db.createUser({
  user: '{{username}}',
  pwd: '{{password}}',
  roles: [
    {
      role: 'dbOwner',
      db: 'remotr'
    }
  ]
})
db.daemons.insertOne({ document: 'test', tags: ['test'], content: 'test' })
db.daemons.deleteOne({ document: { $eq: 'test' } })
